### Create spedition-order
POST localhost/spedition-orders?status=DRAFT
Content-Type: application/json

{
  "creator": {
    "id": "1"
  },
  "contractor": {
    "id": "01HTW3N3VFG7WSDZ8ZAA33XRPV",
    "contactId": "01HTW3N3VF4F6GV75A5JVV43CD"
  },
  "driver": {
    "name": "Jan Kowalski",
    "phoneNumber": "798 558 648",
    "identityCardNumber": "AVC 112TE5"
  },
  "vehicle": {
    "carLicensePlate": "PZ 535CD",
    "trailerLicensePlate": "WX 556AV"
  },
  "loading": {
    "date": 1712700000000,
    "address": "Seaking Poland Ltd Sp. z o.o., ul.Nowa 1B, 64-700 Czarnkow, PL",
    "loadingNumber": "9qwer",
    "additionalInfo": "Dodatkowe informacje dotyczace zaladunku"
  },
  "unloading": {
    "date": 1712872800000,
    "address":
    "I.SEAKING FRANCE S.A.R.L C/O IDEA LOGISTIQUE ,LOGISTICTIPORT, 4 RUE JEAN-BAPTISTE MARCET BATIMENT C, 44570 TRIGNAC, FR",
    "unloadingNumber": "abc44",
    "additionalInfo": "Dodatkowe informacje dotyczace rozaladunku"
  },
  "loadDetails": [],
  "freight": {
    "value": "3500",
    "currency": "PLN",
    "vatRate": 23,
    "paymentDays": 45
  },
  "additionalInfo": "Dodatkowe informacje o zleceniu"
}

### All spedition orders
GET localhost/spedition-orders


### Some spedition order
GET localhost/spedition-orders/01HTJTK8VB3WVAYFDA2AVR4FCD

### change status
PATCH localhost/spedition-orders/01HTQ8R362MFCHR6HEKFBQ7ZG0
Content-Type: application/json

{
  "status": "CREATED"
}