### Create spedition-order
POST localhost/spedition-orders?status=DRAFT
Content-Type: application/json

{
  "creator": {
    "id": "1"
  },
  "contractor": {
    "id": "01HTW3N3VFG7WSDZ8ZAA33XRPV",
    "contactId": "01HTW3N3VF4F6GV75A5JVV43CD"
  },
  "driver": {
    "name": "Jan Kowalski",
    "phoneNumber": "798 558 648",
    "identityCardNumber": "AVC 112TE5"
  },
  "vehicle": {
    "carLicensePlate": "PZ 535CD",
    "trailerLicensePlate": "WX 556AV"
  },
  "loading": {
    "date": 1712700000000,
    "address": "Seaking Poland Ltd Sp. z o.o., ul.Nowa 1B, 64-700 Czarnkow, PL",
    "loadingNumber": "9qwer",
    "additionalInfo": "Dodatkowe informacje dotyczace zaladunku"
  },
  "unloading": {
    "date": 1712872800000,
    "address":
    "I.SEAKING FRANCE S.A.R.L C/O IDEA LOGISTIQUE ,LOGISTICTIPORT, 4 RUE JEAN-BAPTISTE MARCET BATIMENT C, 44570 TRIGNAC, FR",
    "unloadingNumber": "abc44",
    "additionalInfo": "Dodatkowe informacje dotyczace rozaladunku"
  },
  "loadDetails": [],
  "freight": {
    "value": "3500",
    "currency": "PLN",
    "vatRate": 23,
    "paymentDays": 45
  },
  "additionalInfo": "Dodatkowe informacje o zleceniu"
}

### Create spedition-order #11
POST localhost/spedition-orders?status=DRAFT
Content-Type: application/json

{
  "creator": {
    "id": "1"
  },
  "contractor": {
    "id": "01HTZQB5W93J9P5VZW83YQRMPE",
    "contactId": "01HTZQB5W91GSDBJ8SSS7K1EZJ"
  },
  "driver": {
    "name": "",
    "phoneNumber": "",
    "identityCardNumber": ""
  },
  "vehicle": {
    "carLicensePlate": "FG8784P",
    "trailerLicensePlate": "DPL3T25"
  },
  "loading": {
    "date": 1712707200000,
    "address": "EMW Treuen GmbH,\nHerlasgrüner Str. 72, 08233 Treuen, Niemcy",
    "loadingNumber": "A066438403",
    "additionalInfo": "8:00 - 16:00 "
  },
  "unloading": {
    "date": 1712793600000,
    "address": "Gedia Poland Sp. z o.o. \nul. Staszica2 , PL 67-100 Nowa Sól",
    "unloadingNumber": "",
    "additionalInfo": "rozładunek do 23:59"
  },
  "loadDetails": [
    {
      "name": "Stal rolka",
      "value": "24000kg"
    }
  ],
  "freight": {
    "value": "425",
    "vatRate": 23,
    "currency": "EUR",
    "paymentDays": 45
  },
  "status": "CREATED",
  "additionalInfo": "Wymagane czyste, suche auto oraz podstawowy sprzęt do zabezpieczenia ładunku - pasy, narożniki i maty.  Wymagana naczepa Coilmulda + min. 5 łańcuchów do zabezpieczenia towaru. \n "
}

### All spedition orders
GET localhost/spedition-orders


### Some spedition order
GET localhost/spedition-orders/01HTJTK8VB3WVAYFDA2AVR4FCD

### change status
PATCH localhost/spedition-orders/01HTQ8R362MFCHR6HEKFBQ7ZG0
Content-Type: application/json

{
  "status": "CREATED"
}

### Spedition orders feed
GET localhost/spedition-orders-feed
Authorization: token

###
GET localhost/spedition-orders?orderYear=2024&orderMonth=6
Authorization: token